#!/bin/bash

# changes the default shell for the X session
# but doesn't change the shell globally (e.g. chsh), so ssh still uses bash,
# which avoids a bug in Visual Studio's Linux Development tools
export SHELL=/usr/bin/fish

eval `SSH_ASKPASS=ssh-askpass-fullscreen SHELL=/bin/bash /usr/bin/keychain --eval id_rsa`

HOSTNAME=`hostname`
if [[ $HOSTNAME == "plagueis" ]]; then
    # there is probably a better way to make this stick?
    xrandr --output HDMI-1 --left-of HDMI-0
    xrandr --output DVI-D-0 --right-of HDMI-0
fi

dropbox start &
/usr/bin/steam &

exec xmonad
