#!/bin/bash -ex
# ad-hoc script to handoff the rest of the configuration to Saltstack

# as long as it's a private repo, this needs to be run interactively with an ssh key loaded:
# run with sudo -E ./20_bootstrap

REPO_DIR=$HOME/linux-desktop
REPO_URL=git@github.com:TTimo/linux-desktop.git

apt-get install -y git

if [ -d "$REPO_DIR" ]; then
  cd "$REPO_DIR"
  git pull --all
else
  git clone $REPO_URL $REPO_DIR
fi

# /srv/salt and /srv/pillar must exist and symlink to the salt and pillar directories in our code
[ -h /srv/salt ] || ln -s "$REPO_DIR"/salt /srv/salt
[ -h /srv/pillar ] || ln -s "$REPO_DIR"/pillar /srv/pillar
[ -h /srv/formulas ] || ln -s "$REPO_DIR"/formulas /srv/formulas

# configure for masterless operation
cat <<EOF >/etc/salt/minion
id: master
file_client: local
EOF

cat <<EOF >/etc/salt/master
worker_threads: 1
enable_gpu_grains: True
EOF

# seems new salt setup is dropping a default 'minion_id' which we are not ready for
rm -f /etc/salt/minion_id

salt-call --local state.highstate
