#!/bin/bash -ex
# ad-hoc script to handoff the rest of the configuration to Saltstack

if [ -z "$HOME" ] ; then
    REPO_DIR=/root/linux-salted
else
    REPO_DIR=$HOME/linux-salted
fi
REPO_URL=https://github.com/TTimo/linux-salted.git

apt-get install -y git

if [ -d "$REPO_DIR" ]; then
  cd "$REPO_DIR"
  git pull --all
else
  git clone $REPO_URL $REPO_DIR
fi

# /srv/salt and /srv/pillar must exist and symlink to the salt and pillar directories in our code
[ -h /srv/salt ] || ln -s "$REPO_DIR"/salt /srv/salt
[ -h /srv/pillar ] || ln -s "$REPO_DIR"/pillar /srv/pillar
[ -h /srv/formulas ] || ln -s "$REPO_DIR"/formulas /srv/formulas

# configure for masterless operation
cat <<EOF >/etc/salt/minion
id: master
file_client: local
EOF

cat <<EOF >/etc/salt/master
worker_threads: 1
enable_gpu_grains: True
pillar_opts: True
EOF

# seems new salt setup is dropping a default 'minion_id' which we are not ready for
rm -f /etc/salt/minion_id
