#!/bin/bash -ex

FORMULAS_DIR=`readlink -f /srv/formulas`
if [ ! -d $FORMULAS_DIR ] ; then
  mkdir $FORMULAS_DIR
fi

cd /srv/formulas

if [ ! -d steamrt-formula ] ; then
  git clone https://github.com/TTimo/steamrt-formula   
fi
